name: Sync Wiki and Template to README

on:
  push:
  schedule:
    - cron: '0 0 * * *' # 每天运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout Wiki repository
      run: |
        git clone https://github.com/RandallAnjie/RNotification.wiki.git wiki

    - name: Merge content to README
      run: |
        cat README_templet.md > README.md
        echo "\n\n# 使用说明\n\n详情请见[项目wiki](https://github.com/RandallAnjie/RNotification/wiki/使用说明)\n\n" >> README.md
        cat wiki/使用说明.md >> README.md
        echo "\n\n# 更新日志\n\n详情请见[项目wiki](https://github.com/RandallAnjie/RNotification/wiki/更新日志)\n\n" >> README.md
        cat wiki/更新日志.md >> README.md

    - name: Commit changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PUSH_TOKEN }}@github.com/RandallAnjie/RNotification.git
        git add README.md
        git commit -m "Sync Wiki and Template content to README" || echo "No changes to commit"
        git push

